
using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;

public class OcclusionManager : UdonSharpBehaviour
{
    [Header("Areas")]
    [Tooltip("Root objects for each closed area. These will be enabled/disabled.")]
    public GameObject[] m_AreaRoots;

    [Tooltip("Disable distance per area (same length as Area Roots).")]
    public float[] m_AreaDisableDistances;

    [Header("Area Links (Editor-managed)")]
    [Tooltip("Source area index for each link that can force another area to stay active while the player is inside this source area's baked AABB and the source is not force-disabled.")]
    [HideInInspector] public int[] m_AlwaysDisplayLinkSourceAreaIndices;

    [Tooltip("Target area index for each always-display link.")]
    [HideInInspector] public int[] m_AlwaysDisplayLinkTargetAreaIndices;

    [Tooltip("Source area index for each link that can force another area to stay disabled while the player is inside this source area's baked AABB.")]
    [HideInInspector] public int[] m_AlwaysDisableLinkSourceAreaIndices;

    [Tooltip("Target area index for each always-disable link. Disable links win over display links if both target the same area.")]
    [HideInInspector] public int[] m_AlwaysDisableLinkTargetAreaIndices;

    [Header("Baked Bounds (Editor-generated)")]
    [Tooltip("World-space AABB center for each area. Generated by the editor tool.")]
    public Vector3[] m_AreaBoundsCenter;

    [Tooltip("World-space AABB extents for each area. Generated by the editor tool.")]
    public Vector3[] m_AreaBoundsExtents;

    [Header("Timing")]
    [Tooltip("Seconds to wait after enable before starting checks.")]
    public float m_StartDelaySeconds = 2f;

    [Tooltip("Checks per second. Higher = more responsive, more CPU.")]
    [Min(0.1f)]
    public float m_TicksPerSecond = 2f;

    [System.NonSerialized] private bool _loopActive;
    [System.NonSerialized] private bool[] _areaBaseActive;
    [System.NonSerialized] private bool[] _areaPlayerInsideBounds;
    [System.NonSerialized] private bool[] _areaForceDisplay;
    [System.NonSerialized] private bool[] _areaForceDisable;
    [System.NonSerialized] private bool[] _areaCanProcessLinks;
    [System.NonSerialized] private bool[] _areaDisableSourceResolved;
    [System.NonSerialized] private bool[] _areaWasInsideBounds;
    [System.NonSerialized] private float[] _areaContainmentDepth;
    [System.NonSerialized] private int[] _areaInsideEntryOrder;
    [System.NonSerialized] private int _areaEntrySequence;

    private static bool IsFinite(float v)
    {
        return !(float.IsNaN(v) || float.IsInfinity(v));
    }

    private static bool IsFinite(Vector3 v)
    {
        return IsFinite(v.x) && IsFinite(v.y) && IsFinite(v.z);
    }

    private static float GetHorizontalContainmentDepth(Vector3 playerPos, Vector3 min, Vector3 max)
    {
        float xDepth = playerPos.x - min.x;
        float xDepthMax = max.x - playerPos.x;
        if (xDepthMax < xDepth) xDepth = xDepthMax;

        float zDepth = playerPos.z - min.z;
        float zDepthMax = max.z - playerPos.z;
        if (zDepthMax < zDepth) zDepth = zDepthMax;

        float depth = xDepth;
        if (zDepth < depth) depth = zDepth;
        if (depth < 0f) depth = 0f;
        return depth;
    }

    private void OnEnable()
    {
        _loopActive = true;

        float delay = m_StartDelaySeconds;
        if (!IsFinite(delay)) delay = 0f;
        delay = Mathf.Max(0f, delay);

        SendCustomEventDelayedSeconds(nameof(_Tick), delay);
    }

    private void OnDisable()
    {
        _loopActive = false;
    }

    public override void OnPlayerRespawn(VRCPlayerApi player)
    {
        if (!_loopActive) return;
        if (!Utilities.IsValid(player)) return;

        VRCPlayerApi lp = Networking.LocalPlayer;
        if (!Utilities.IsValid(lp)) return;
        if (player.playerId != lp.playerId) return;

        // Force an immediate tick for the local respawn without creating an extra scheduled loop.
        _TickInternal();
    }

    public void _Tick()
    {
        if (!_loopActive) return;

        // Schedule next tick first (so early returns still keep timing stable).
        float tps = m_TicksPerSecond;
        if (!IsFinite(tps)) tps = 2f;
        tps = Mathf.Max(0.1f, tps);
        float interval = 1f / tps;
        SendCustomEventDelayedSeconds(nameof(_Tick), interval);

        _TickInternal();
    }

    public void _TickInternal()
    {
        if (!_loopActive) return;

        VRCPlayerApi lp = Networking.LocalPlayer;
        if (!Utilities.IsValid(lp)) return;

        Vector3 playerPos = lp.GetPosition();
        if (!IsFinite(playerPos)) return;

        int n = (m_AreaRoots != null) ? m_AreaRoots.Length : 0;
        if (n <= 0) return;

        // Require baked data. If arrays are missing/mismatched, skip (don't auto-build at runtime).
        if (m_AreaBoundsCenter == null || m_AreaBoundsExtents == null) return;
        if (m_AreaBoundsCenter.Length != n || m_AreaBoundsExtents.Length != n) return;
        if (m_AreaDisableDistances == null || m_AreaDisableDistances.Length != n) return;

        EnsureAreaStateBuffers(n);

        // Phase 1: compute the base distance state, source AABB containment, and clear force flags.
        for (int i = 0; i < n; i++)
        {
            bool wasInside = _areaWasInsideBounds[i];

            _areaBaseActive[i] = false;
            _areaPlayerInsideBounds[i] = false;
            _areaForceDisplay[i] = false;
            _areaForceDisable[i] = false;
            _areaCanProcessLinks[i] = false;
            _areaDisableSourceResolved[i] = false;
            _areaContainmentDepth[i] = 0f;

            GameObject root = m_AreaRoots[i];
            if (root == null)
            {
                _areaWasInsideBounds[i] = false;
                _areaInsideEntryOrder[i] = 0;
                continue;
            }

            float dist = m_AreaDisableDistances[i];
            if (!IsFinite(dist)) dist = 500f;
            if (dist < 0f) dist = 0f;
            float distSqr = dist * dist;

            Vector3 c = m_AreaBoundsCenter[i];
            Vector3 e = m_AreaBoundsExtents[i];

            // If baked bounds are invalid or absurdly large, fall back to the root position.
            // This prevents a single huge/NaN renderer from making the player appear "inside" a far-away room at spawn.
            bool boundsOk = IsFinite(c) && IsFinite(e) && e.x >= 0f && e.y >= 0f && e.z >= 0f;
            const float MAX_EXTENT = 20000f;
            if (!boundsOk || e.x > MAX_EXTENT || e.y > MAX_EXTENT || e.z > MAX_EXTENT)
            {
                c = root.transform.position;
                e = Vector3.zero;
            }

            // Closest point on AABB.
            Vector3 min = c - e;
            Vector3 max = c + e;
            Vector3 closest;
            closest.x = Mathf.Clamp(playerPos.x, min.x, max.x);
            closest.y = Mathf.Clamp(playerPos.y, min.y, max.y);
            closest.z = Mathf.Clamp(playerPos.z, min.z, max.z);

            Vector3 d = playerPos - closest;
            float sqr = (d.x * d.x) + (d.y * d.y) + (d.z * d.z);

            bool shouldDisable = sqr > distSqr;
            bool playerInsideBounds = sqr <= 0.000001f;
            _areaBaseActive[i] = !shouldDisable;
            _areaPlayerInsideBounds[i] = playerInsideBounds;
            _areaCanProcessLinks[i] = playerInsideBounds;

            if (playerInsideBounds)
            {
                _areaContainmentDepth[i] = GetHorizontalContainmentDepth(playerPos, min, max);
                if (!wasInside || _areaInsideEntryOrder[i] <= 0)
                {
                    _areaEntrySequence++;
                    if (_areaEntrySequence <= 0) _areaEntrySequence = 1;
                    _areaInsideEntryOrder[i] = _areaEntrySequence;
                }
            }
            else
            {
                _areaInsideEntryOrder[i] = 0;
            }

            _areaWasInsideBounds[i] = playerInsideBounds;
        }

        // Phase 2: Resolve disable links until disabled areas have been fully removed from the graph.
        ResolveDisableLinksToStableState(n);

        // Phase 3: Apply display links using only areas that survived disable resolution.
        ApplyDisplayLinks(n);

        // Phase 4: apply final state. Disable wins over display, display wins over base distance.
        for (int i = 0; i < n; i++)
        {
            GameObject root = m_AreaRoots[i];
            if (root == null) continue;

            bool shouldBeActive = _areaBaseActive[i];
            if (_areaForceDisplay[i]) shouldBeActive = true;
            if (_areaForceDisable[i]) shouldBeActive = false;

            if (root.activeSelf != shouldBeActive)
            {
                root.SetActive(shouldBeActive);
            }
        }
    }

    private void EnsureAreaStateBuffers(int areaCount)
    {
        if (_areaBaseActive != null && _areaBaseActive.Length == areaCount &&
            _areaPlayerInsideBounds != null && _areaPlayerInsideBounds.Length == areaCount &&
            _areaForceDisplay != null && _areaForceDisplay.Length == areaCount &&
            _areaForceDisable != null && _areaForceDisable.Length == areaCount &&
            _areaCanProcessLinks != null && _areaCanProcessLinks.Length == areaCount &&
            _areaDisableSourceResolved != null && _areaDisableSourceResolved.Length == areaCount &&
            _areaWasInsideBounds != null && _areaWasInsideBounds.Length == areaCount &&
            _areaContainmentDepth != null && _areaContainmentDepth.Length == areaCount &&
            _areaInsideEntryOrder != null && _areaInsideEntryOrder.Length == areaCount)
        {
            return;
        }

        _areaBaseActive = new bool[areaCount];
        _areaPlayerInsideBounds = new bool[areaCount];
        _areaForceDisplay = new bool[areaCount];
        _areaForceDisable = new bool[areaCount];
        _areaCanProcessLinks = new bool[areaCount];
        _areaDisableSourceResolved = new bool[areaCount];
        _areaWasInsideBounds = new bool[areaCount];
        _areaContainmentDepth = new float[areaCount];
        _areaInsideEntryOrder = new int[areaCount];
        _areaEntrySequence = 0;
    }

    private void ResolveDisableLinksToStableState(int areaCount)
    {
        if (m_AlwaysDisableLinkSourceAreaIndices == null || m_AlwaysDisableLinkTargetAreaIndices == null) return;

        while (true)
        {
            int sourceIndex = FindHighestPriorityDisableSource(areaCount);
            if (sourceIndex < 0) break;

            _areaDisableSourceResolved[sourceIndex] = true;
            ApplyDisableLinksFromSource(sourceIndex, areaCount);
        }
    }

    private int FindHighestPriorityDisableSource(int areaCount)
    {
        int bestIndex = -1;

        for (int i = 0; i < areaCount; i++)
        {
            if (!_areaCanProcessLinks[i]) continue;
            if (_areaDisableSourceResolved[i]) continue;
            if (bestIndex < 0 || IsAreaHigherPriority(i, bestIndex)) bestIndex = i;
        }

        return bestIndex;
    }

    private bool IsAreaHigherPriority(int areaIndex, int otherAreaIndex)
    {
        float depth = _areaContainmentDepth[areaIndex];
        float otherDepth = _areaContainmentDepth[otherAreaIndex];
        const float DEPTH_EPSILON = 0.001f;

        if (depth > otherDepth + DEPTH_EPSILON) return true;
        if (otherDepth > depth + DEPTH_EPSILON) return false;

        int entryOrder = _areaInsideEntryOrder[areaIndex];
        int otherEntryOrder = _areaInsideEntryOrder[otherAreaIndex];

        if (entryOrder > 0 && otherEntryOrder > 0 && entryOrder != otherEntryOrder)
        {
            return entryOrder < otherEntryOrder;
        }

        if (entryOrder > 0 && otherEntryOrder <= 0) return true;
        if (otherEntryOrder > 0 && entryOrder <= 0) return false;

        return areaIndex < otherAreaIndex;
    }

    private void ApplyDisableLinksFromSource(int sourceAreaIndex, int areaCount)
    {
        int linkCount = m_AlwaysDisableLinkSourceAreaIndices.Length;
        if (m_AlwaysDisableLinkTargetAreaIndices.Length < linkCount) linkCount = m_AlwaysDisableLinkTargetAreaIndices.Length;

        for (int i = 0; i < linkCount; i++)
        {
            int sourceIndex = m_AlwaysDisableLinkSourceAreaIndices[i];
            if (sourceIndex != sourceAreaIndex) continue;

            int targetIndex = m_AlwaysDisableLinkTargetAreaIndices[i];
            if (targetIndex < 0 || targetIndex >= areaCount) continue;
            if (_areaCanProcessLinks[targetIndex] && IsAreaHigherPriority(targetIndex, sourceAreaIndex)) continue;

            ForceDisableArea(targetIndex);
        }
    }

    private void ForceDisableArea(int areaIndex)
    {
        _areaForceDisable[areaIndex] = true;
        _areaForceDisplay[areaIndex] = false;
        _areaCanProcessLinks[areaIndex] = false;
    }

    private void ApplyDisplayLinks(int areaCount)
    {
        if (m_AlwaysDisplayLinkSourceAreaIndices == null || m_AlwaysDisplayLinkTargetAreaIndices == null) return;

        int linkCount = m_AlwaysDisplayLinkSourceAreaIndices.Length;
        if (m_AlwaysDisplayLinkTargetAreaIndices.Length < linkCount) linkCount = m_AlwaysDisplayLinkTargetAreaIndices.Length;

        for (int i = 0; i < linkCount; i++)
        {
            int sourceIndex = m_AlwaysDisplayLinkSourceAreaIndices[i];
            int targetIndex = m_AlwaysDisplayLinkTargetAreaIndices[i];

            if (sourceIndex < 0 || sourceIndex >= areaCount) continue;
            if (targetIndex < 0 || targetIndex >= areaCount) continue;
            if (!_areaCanProcessLinks[sourceIndex]) continue;
            if (_areaForceDisable[targetIndex]) continue;

            _areaForceDisplay[targetIndex] = true;
        }
    }
}
